EXP_NAME: viper2city_PixMatch
SOURCE: Viper
DATA_DIRECTORY_SOURCE: ../../data/Viper
DATA_LIST_SOURCE: ../dataset/Viper_list/train.txt
NUM_CLASSES: 15
NUM_WORKERS: 4
TRAIN:
  LEARNING_RATE: 0.00025
  EARLY_STOP: 40000
  SCALING_RATIO:
    - 0.8
    - 1.2
  flow_path_src: ../../data/estimated_optical_flow_viper_train
  DA_METHOD: TPS
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_Viper.json
  INPUT_SIZE_SOURCE:
      - 1280
      - 720
  SNAPSHOT_DIR: ../../experiments/snapshots/pixmatch_viper2city
  SAVE_PRED_EVERY: 100
TEST:
  SNAPSHOT_DIR: ['../../experiments/snapshots/pixmatch_viper2city']
  MODE: video_best
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_Viper.json
  SNAPSHOT_STEP: 100
  SNAPSHOT_START_ITER: 100
