EXP_NAME: syn2city_source_only
SOURCE: SynthiaSeq
DATA_DIRECTORY_SOURCE: ../../data/SynthiaSeq/SEQS-04-DAWN
DATA_LIST_SOURCE: ../dataset/SynthiaSeq_list/train.txt
### train on 12 classes and evaluate on 11 classes
NUM_CLASSES: 12
TRAIN:
  EARLY_STOP: 40000
  flow_path_src: ../../data/Estimated_optical_flow_SynthiaSeq_train
  DA_METHOD: SourceOnly
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SET_SOURCE: train
  SAVE_PRED_EVERY: 1000
  INPUT_SIZE_SOURCE:
    - 1280
    - 640
TEST:
  SNAPSHOT_STEP: 1000
  SNAPSHOT_START_ITER: 1000
  MODE: video_best
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_SynthiaSeq.json
