EXP_NAME: viper2city_source_only
SOURCE: Viper
DATA_DIRECTORY_SOURCE: ../../data/Viper
DATA_LIST_SOURCE: ../dataset/Viper_list/train.txt
NUM_CLASSES: 15
NUM_WORKERS: 4
TRAIN:
  EARLY_STOP: 40000
  SAVE_PRED_EVERY: 1000
  flow_path_src: ../../data/Estimated_optical_flow_Viper_train
  DA_METHOD: SourceOnly
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_Viper.json
  INPUT_SIZE_SOURCE:
    - 1280
    - 720
TEST:
  SNAPSHOT_STEP: 1000
  SNAPSHOT_START_ITER: 1000
  MODE: video_best
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_Viper.json
