EXP_NAME: syn2city_TempMatch
SOURCE: SynthiaSeq
DATA_DIRECTORY_SOURCE: ../../data/SynthiaSeq/SEQS-04-DAWN
DATA_LIST_SOURCE: ../dataset/SynthiaSeq_list/train.txt
NUM_CLASSES: 12
TRAIN:
  LEARNING_RATE: 0.00025
  EARLY_STOP: 40000
  SCALING_RATIO:
    - 0.8
    - 1.2
  flow_path_src: ../../data/Estimated_optical_flow_SynthiaSeq_train
  DA_METHOD: TemporalMatch
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SET_SOURCE: train
  INPUT_SIZE_SOURCE:
    - 1280
    - 640
  SNAPSHOT_DIR: ../../experiments/snapshots/syn2city_tmp_4.0
  SAVE_PRED_EVERY: 100
TEST:
  MODE: video_best
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SNAPSHOT_DIR: ['../../experiments/snapshots/syn2city_tmp_4.0']
  SNAPSHOT_STEP: 100
  SNAPSHOT_START_ITER: 100
