EXP_NAME: syn2city_TPS
SOURCE: SynthiaSeq
DATA_DIRECTORY_SOURCE: ../../data/SynthiaSeq/SEQS-04-DAWN
DATA_LIST_SOURCE: ../dataset/SynthiaSeq_list/train.txt
NUM_CLASSES: 12
TRAIN:
  LEARNING_RATE: 0.00025
  EARLY_STOP: 40000
  SCALING_RATIO:
    - 0.8
    - 1.2
  flow_path_src: ../../data/estimated_optical_flow_synthiaseq_train
  DA_METHOD: TPS
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SET_SOURCE: train
  INPUT_SIZE_SOURCE:
    - 1280
    - 640
  SNAPSHOT_DIR: ../../experiments/snapshots/tps_syn2city
  SAVE_PRED_EVERY: 100
TEST:
  MODE: video_best
  INFO_TARGET: ../dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SNAPSHOT_DIR: ['../../experiments/snapshots/tps_syn2city']
  SNAPSHOT_STEP: 100
  SNAPSHOT_START_ITER: 100
